languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "æ±äº¬ãƒ¤ã‚¯ãƒ«ãƒˆã‚¹ãƒ¯ãƒ­ãƒ¼ã‚º"
# logo = "img/blowfish_logo_transparent.png"
description = "Another perfect day"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "ğŸ‰äºŒé€£è¦‡ãŠã‚ã§ã¨ã†ã”ã–ã„ã¾ã™ğŸ»ï¼"
  # image = "img/blowfish_logo.png"
  headline = "![1](/img/20220925_223534.jpg)"
  bio = "to tyou's world"
  links = [
    { email = "changingmoments.tyou@gmail.com" },
    { github = "https://github.com/sikonn" },
    { mastodon = "https://ramen-fsm.tk/web/@food" },
  ]
